version: '3.8'

services:
  db:
    image: postgres:15.4-alpine3.18
    container_name: todo-postgres
    environment:
      POSTGRES_DB: "kachi"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "25432:5432"
    volumes:
      - db-store:/var/lib/postgresql/data
    networks:
      - kachi_net

volumes:
  db-store:
  pgadmin:

networks:
  kachi_net:
    driver: bridge